name: voiceshadow
description: Voice cloning and shadowing application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Firebase (Web compatible versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # Audio & Media (Web compatible)
  record: ^5.0.4
  audioplayers: ^5.2.1
  permission_handler: ^11.1.0
  
  
  # Web specific
  flutter_web_plugins:
    sdk: flutter
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  
  # Utils
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # Timer for recording
  async: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
